# Generated by Django 5.0 on 2024-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_apellidos', models.CharField(max_length=90)),
                ('Perfil', models.CharField(choices=[('administrativo', 'Administrativo'), ('aprendiz', 'Aprendiz'), ('estudiante', 'Estudiante'), ('docente', 'Docente')], max_length=50)),
                ('Facultad', models.CharField(choices=[('Psicología', 'Psicología'), ('Matemáticas', 'Matemáticas'), ('Física', 'Física')], max_length=90)),
                ('Telefono', models.IntegerField()),
                ('Correo', models.CharField(max_length=90)),
                ('Nro_portatil', models.IntegerField()),
                ('Fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('Observaciones', models.CharField(max_length=100)),
            ],
        ),
    ]
