# Generated by Django 5.0 on 2024-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
